<?php
/*
 * Generated by CRUDigniter v3.2
 * www.crudigniter.com
 */


 require __DIR__ . '/../../vendor/mike42/escpos-php/autoload.php';
 use Mike42\Escpos\Printer;
 use Mike42\Escpos\PrintConnectors\WindowsPrintConnector;

 //use Mike42\Escpos\Printer;
 //use Mike42\Escpos\PrintConnectors\WindowsPrintConnector;
class Impressoras extends CI_Controller{

  public function __construct() {
   parent::__construct();
  // $this->load->library('escpos');


}

    function impressaoteste(){




    }
  }
